name: Build and Test with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build

  run-playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    needs: build-package
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm playwright install chromium

      - name: Start Applications
        run: |
          pnpm run dev-rv & # Start the Rust-Vite app on port 5172
        #   pnpm run dev-vv vite-vite & # Start the Vite-Vite app on port 3002
        #   pnpm run dev-nv & # Start the Rust-Vite app on port 3003
        #   pnpm run multi-example & # Start the Vite-Webpack.Rspack app on port 3004

      - name: Wait for apps to be ready
        run: |
          pnpm add wait-on
            wait-on http://localhost:5172
        #   wait-on http://localhost:3001 http://localhost:3002 http://localhost:3003 http://localhost:3004

      - name: Run Playwright Tests
        # run: pnpm playwright test --project=nuxt-vite --project=vite-vite --project=rust-vite --project=vite-webpackrspack
        run: pnpm playwright test --project=rust-vite
