name: Build and Test with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  run-playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    container: node:20
    strategy:
      matrix:
        project: [vite-vite, vite-webpack-rspack]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack and Setup PNPM
        run: |
          corepack enable
          corepack prepare pnpm@9.1.3 --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chromium Browser
        run: pnpm playwright install --with-deps chromium

      - name: Build Projects
        run: pnpm build

      - name: Start Application (${{ matrix.project }})
        run: |
          if [ "${{ matrix.project }}" = "vite-vite" ]; then
            nohup pnpm run dev-vv & 
            pnpm exec wait-on http://localhost:5175;
          else
            nohup pnpm run multi-example & 
            pnpm exec wait-on http://localhost:5173;
          fi

      - name: Run Playwright Tests (${{ matrix.project }})
        run: pnpm playwright test --project=${{ matrix.project }}

      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.project }}
          path: reports/e2e/output
          retention-days: 3
