name: Build and Test with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  run-playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chromium Browser
        run: pnpm playwright install --with-deps chromium

      - name: Build Projects
        run: pnpm build

      # - name: Start Vite Application
      #   run: |
      #     nohup pnpm run dev-vv &

      # - name: Wait for Vite to be Ready
      #   run: pnpm exec wait-on http://localhost:5175

      # - name: Run Playwright Tests
      #   run: pnpm playwright test --project=vite-vite

      # Although the server starts, Playwright is unable to access it; the network is not reachable.
      # - name: Start Rust-Vite Application
      #   run: |
      #     nohup pnpm run dev-rv &

      # - name: Wait for Vite to be Ready
      #   run: pnpm exec wait-on http://localhost:5172

      # - name: Run Playwright Tests
      #   run: pnpm playwright test --project=rust-vite

      - name: Start Multi Example Application
        run: |
          nohup pnpm run multi-example &

      - name: Wait for Application to be Ready
        run: pnpm exec wait-on http://localhost:5173

      - name: Run Playwright Tests
        run: pnpm playwright test --project=vite-webpack-rspack

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: reports/e2e/output
          retention-days: 30
